# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://andrewt-cville.github.io/fb_recruiting/"

git_url = "https://github.com/andrewt-cville/fb_recruiting/tree/master/"

def custom_doc_links(name): return None
